version: 2
updates:
# GitHub Actions and workflows
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - gsuquet
  assignees:
  - gsuquet
  target-branch: main
  commit-message:
    prefix: ':arrow_up: chore(ci)'

# Docker
- package-ecosystem: docker
  directory: /.devcontainer
  schedule:
    interval: weekly
  reviewers:
  - gsuquet
  assignees:
  - gsuquet
  target-branch: main
  commit-message:
    prefix: ':money_with_wings: chore(docker)'
