- name: ignore-for-release
  color: E707F8
  description: dont store in release notes
- name: breaking-change
  color: E99695
  description: Breaking change for user
- name: bug
  color: d73a4a
  description: Something isn't working
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: configuration
  color: 568b59
  description: Changes to the configuration files
- name: ci
  color: 969b96
  description: Changes to the CI/CD pipeline
- name: github_actions
  color: 0a0a0a
  description: GitHub Actions and Workflows
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: question
  color: d876e3
  description: Further information is requested
- name: Semver-Major
  color: f9d0c4
  description: Major Version release
- name: Semver-Minor
  color: 0E8A16
  description: minor change
- name: wontfix
  color: ffffff
  description: This will not be worked on
