name: New feature ✨
description: Suggest a new feature or other improvement
labels: [enhancement, to sort]
body:
- type: markdown
  attributes:
    value: |
      ## New feature Request
- type: textarea
  id: spec
  attributes:
    label: Feature Spec
    placeholder: |
      Describe the feature as if it was already released. Write a hypothetical doc/readme/changelog/contributing section for this new enhancement, code snippets and all.
  validations:
    required: true
- type: textarea
  id: use-cases
  attributes:
    label: Use Cases
    placeholder: |
      What problems does this solves? List of use cases this feature or enhancement is designed to address.
  validations:
    required: true
- type: textarea
  id: implementation-notes
  attributes:
    label: Implementation Notes
    placeholder: |
      Any thoughts regarding how this should be implemented?
- type: dropdown
  id: Components
  attributes:
    label: Components
    description: Which component(s) in the toolchain is this related to?
    multiple: true
    options:
    - Automation
    - Deployment
    - Integration
    - Pages
    - Monitoring
    - Security
    - Documentation
    - Other
  validations:
    required: true
