major_tags:
- ':boom:'
minor_tags:
- ':sparkles:'
patch_tags:
- ':ambulance:'
- ':bug:'
- ':adhesive_bandage:'
- ':lock:'
- ':arrow_up:'
- ':arrow_down:'
- ':heavy_plus_sign:'
- ':heavy_minus_sign:'
- ':rotating_light:'
- ':zap:'
- ':recycle:'
- ':wrench:'
- ':loud_sound:'
- ':mute:'
- ':goal_net:'
- ':wastebasket:'
- ':coffin:'
- ':chart_with_upwards_trend:'
- ':globe_with_meridians:'
- ':alien:'
- ':wheelchair:'
- ':children_crossing:'
- ':bricks:'
