name: PR name linter

on:
  workflow_call:

jobs:
  lint_pr_name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        npm install commitlint-config-gitmoji commitlint
        echo "module.exports = {extends: ['gitmoji']};" > ./commitlint.config.js
    - name: Run PR name linter
      uses: JulienKode/pull-request-name-linter-action@v0.5.0
