name: Greetings

on:
  workflow_call:
    inputs:
      issue_message:
        description: The message to post on user's first issue
        required: true
        type: string
        default: Welcome to the repo!
      pr_message:
        description: The message to post on user's first PR
        required: true
        type: string
        default: Thanks for the PR!

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: ${{ inputs.issue_message }}
        pr-message: ${{ inputs.pr_message }}
