name: Labeler

on:
  pull_request:
    types: [opened, synchronize, edited]

  workflow_call:
    inputs:
      config_path:
        description: Path to the configuration file
        required: false
        type: string
        default: .github/labeler.yml

permissions: {}

concurrency:
  group: labeler-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
      with:
        configuration-path: ${{ inputs.config_path || '.github/labeler.yml' }}
