name: Labeler

on:
  pull_request:
    types: [opened, synchronize, edited]

  workflow_call:
    inputs:
      config_path:
        description: Path to the configuration file
        required: false
        type: string
        default: .github/labeler.yml
      harden_runner:
        description: "Harden the runner"
        required: false
        default: true
        type: boolean

permissions: {}

concurrency:
  group: labeler-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      if: ${{ inputs.harden_runner != false }}
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - name: Apply labels
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        configuration-path: ${{ inputs.config_path || '.github/labeler.yml' }}
