name: Upload files to AWS S3
on:
  workflow_call:
    inputs:
      aws_region:
        description: AWS region
        required: false
        type: string
        default: eu-west-1
      files_path:
        description: The path to the files to copy
        required: false
        type: string
        default: .
      artifact_name:
        description: The name of the artifact to download
        required: false
        type: string
      harden_runner:
        description: "Harden the runner"
        required: false
        default: true
        type: boolean
    secrets:
      bucket_path:
        required: true
        description: The path to the S3 bucket to copy files to
      aws_access_key_id:
        required: true
        description: The AWS access key ID
      aws_secret_access_key:
        required: true
        description: The AWS secret access key

permissions: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      if: ${{ inputs.harden_runner != false }}
      with:
        egress-policy: audit

    - name: Download artifacts
      if: ${{ inputs.artifact_name }}
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.files_path }}

    - name: Copy files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      run: |
        aws s3 cp \
          --recursive \
          --region ${{ inputs.aws_region }} \
          ${{ inputs.files_path }} \
          s3://${{ secrets.bucket_path }}
