name: Upload files to AWS S3
on:
  workflow_call:
    inputs:
      aws_region:
        description: AWS region
        required: false
        type: string
        default: eu-west-1
      files_path:
        description: The path to the files to copy
        required: false
        type: string
        default: .
      artifact_name:
        description: The name of the artifact to download
        required: false
        type: string
    secrets:
      bucket_path:
        required: true
        description: The path to the S3 bucket to copy files to
      aws_access_key_id:
        required: true
        description: The AWS access key ID
      aws_secret_access_key:
        required: true
        description: The AWS secret access key

permissions: read-all

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      if: ${{ inputs.artifact_name }}
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.files_path }}

    - name: Copy files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      run: |
        aws s3 cp \
          --recursive \
          --region ${{ inputs.aws_region }} \
          ${{ inputs.files_path }} \
          s3://${{ secrets.bucket_path }}
