name: Deploy a python package to PyPi and GitHub
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to deploy to'
        default: 'pypi'
      environment_url:
        required: true
        type: string
        description: 'The environment URL to deploy to'
      project_install_command:
        required: false
        type: string
        description: 'The command to install the project'
        default: 'just install'
      project_build_command:
        required: false
        type: string
        description: 'The command to build the project'
        default: 'just build'
      use_just:
        default: true
        description: 'Use just to run commands'
        required: false
        type: boolean
      harden_runner:
        default: true
        description: 'Harden the runner'
        required: false
        type: boolean

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Semantic release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@c82bd673c30da94a02e039963c8c4c8a51758096
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install just
        if: ${{ inputs.use_just }}
        run: sudo snap install --edge --classic just

      - name: Install dependencies
        if: steps.semantic-release.outputs.released == 'true'
        run: ${{ inputs.project_install_command }}

      - name: Build project
        if: steps.semantic-release.outputs.released == 'true'
        run: ${{ inputs.project_build_command }}

      - name: Publish to PyPi
        if: steps.semantic-release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@e53eb8b103ffcb59469888563dc324e3c8ba6f06

      - name: Publish to GitHub
        if: steps.semantic-release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@0f96c02a48278aff14251e9f1a0d73122a8c638b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
