name: Code integration

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
    - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  label:
    uses: ./.github/workflows/automation-labeler.yml
    permissions:
      contents: read
      pull-requests: write

  lint-pr-title:
    if: ${{ github.actor != 'dependabot[bot]'  && github.actor != 'allcontributors[bot]' }}
    uses: ./.github/workflows/integration-commit-validator.yml
    with:
      commit_or_pr_title: ${{ github.event.pull_request.title }}
      format: gitmoji

  dependency-review:
    uses: ./.github/workflows/security-dependencies.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      comment: always

  pre-commit:
    if: ${{ github.actor != 'dependabot[bot]'  && github.actor != 'allcontributors[bot]' }}
    uses: ./.github/workflows/integration-linter-pre-commit.yml

  update-workflows-list:
    uses: ./.github/workflows/integration-modification-script.yml
    permissions:
      contents: write
    with:
      script_path: ./scripts/generate_workflows_table.sh
      ref: ${{ github.head_ref }}
      commit_message: ':memo: doc: Update workflow list in README.md'
