name: Unit tests and code format checks for a python project
on:
  workflow_call:
    inputs:
      python_version:
        default: '3.12'
        description: 'Python version'
        required: true
        type: string
      check_format_command:
        default: 'just check-format'
        description: 'Check format command'
        required: false
        type: string
      install_command:
        default: 'just install'
        description: 'Install command'
        required: false
        type: string
      test_command:
        default: 'just test'
        description: 'Test command'
        required: false
        type: string
      use_just:
        default: true
        description: 'Use just to run commands'
        required: false
        type: boolean
      harden_runner:
        default: true
        description: 'Harden the runner'
        required: false
        type: boolean
      codecov_slug:
        description: 'Codecov slug'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false

jobs:
  code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Check code format
        run: ${{ inputs.check_format_command }}

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Run unit tests
        run: ${{ inputs.test_command }}

      - name: Upload coverage report to Codecov
        if: ${{ inputs.codecov_slug != null }}
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab
        with:
          token: ${{ secrets.codecov_token }}
          slug: ${{ inputs.codecov_slug }}

