name: Unit tests and code format checks for a python project
on:
  workflow_call:
    inputs:
      python_version:
        default: '3.12'
        description: 'Python versions to test against, e.g. `3.11,3.12`'
        required: true
        type: string
      check_format_command:
        default: 'just check-format'
        description: 'Check format command'
        required: false
        type: string
      install_command:
        default: 'just install'
        description: 'Install command'
        required: false
        type: string
      test_command:
        default: 'just test'
        description: 'Test command'
        required: false
        type: string
      use_just:
        default: true
        description: 'Use just to run commands'
        required: false
        type: boolean
      harden_runner:
        default: true
        description: 'Harden the runner'
        required: false
        type: boolean
      codecov_slug:
        description: 'Codecov slug'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false

permissions: {}

concurrency:
  group: integration-python-${{ github.repository }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  code-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_version) }}
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Check code format
        run: ${{ inputs.check_format_command }}

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_version) }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Run unit tests
        run: ${{ inputs.test_command }}

      - name: Upload coverage report to Codecov
        if: ${{ inputs.codecov_slug != null }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.codecov_token }}
          slug: ${{ inputs.codecov_slug }}

