name: Pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version, default is 3.12.x
        required: false
        type: string
        default: 3.12.x
      cache:
        description: Package manager to cache from pip, pipenv and poetry
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit hooks on all files
      run: pre-commit run --all-files --show-diff-on-failure | tee output.txt

    - name: Set pre-commit result as output
      id: pre-commit
      run: |
        output=$(cat output.txt)
        output=$(echo "$output" | sed 's/\[INFO\]/\n- \[INFO\]/g')
        output=$(echo "$output" | grep -v '\[INFO\]')
        output=$(echo "$output" | sed 's/Passed/Passed\n/g')
        output=$(echo "$output" | sed 's/Skipped/Skipped\n/g')

        echo "### Pre-commit result" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`$output\`\`\`" >> $GITHUB_STEP_SUMMARY
      shell: bash
