name: Unit tests and code format checks for a python project
on:
  workflow_call:
    inputs:
      python_version:
        default: '3.12'
        description: 'Python versions to test against, e.g. `3.11,3.12`'
        required: false
        type: string
      check_format_command:
        default: 'just check-format'
        description: 'Check format command'
        required: false
        type: string
      install_command:
        default: 'just install'
        description: 'Install command'
        required: false
        type: string
      test_command:
        default: 'just test'
        description: 'Test command'
        required: false
        type: string
      use_just:
        default: true
        description: 'Use just to run commands'
        required: false
        type: boolean
      harden_runner:
        default: true
        description: 'Harden the runner'
        required: false
        type: boolean
      codecov_slug:
        description: 'Codecov slug'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false

permissions: {}

concurrency:
  group: integration-python-${{ github.repository }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.create-matrix.outputs.versions }}
    steps:
      - name: Create python versions matrix
        id: create-matrix
        run: |
          python-versions="[\"${{ inputs.python_version }} | sed "s/,/\",\"/g")\"]"
          echo "versions=$python-versions" >> $GITHUB_OUTPUT

  code-format:
    runs-on: ubuntu-latest
    needs: [setup]
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.setup.outputs.python-versions) }}
    steps:
      - uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Check code format
        run: ${{ inputs.check_format_command }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: [setup]
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.setup.outputs.python-versions) }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        if: ${{ inputs.harden_runner == true }}
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install just
        if: ${{ inputs.use_just == true }}
        run: sudo snap install --edge --classic just

      - name: Install python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Run unit tests
        run: ${{ inputs.test_command }}

      - name: Upload coverage report to Codecov
        if: ${{ inputs.codecov_slug != null }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.codecov_token }}
          slug: ${{ inputs.codecov_slug }}

