name: Dependency Scanning
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
    - main

  workflow_call:
    inputs:
      severity:
        description: Severity to fail on from low, moderate, high, or critical
        required: false
        type: string
        default: low
      comment:
        description: Comment on PR, from never, always, or on-failure
        required: false
        type: string
        default: on-failure
      harden_runner:
        description: "Harden the runner"
        required: false
        default: true
        type: boolean

permissions: {}

concurrency:
  group: dependency-review-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      if: ${{ inputs.harden_runner != false }}
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.deps.dev:443
          api.github.com:443
          api.securityscorecards.dev:443
          github.com:443

    - name: Checkout Repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

    - name: Dependency Review
      uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a
      with:
        fail-on-severity: ${{ inputs.severity || 'low' }}
        comment-summary-in-pr: ${{ inputs.comment || 'always' }}
