name: Code analysis using Codacy
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch: {}
  workflow_call:
    inputs:
      harden_runner:
        description: 'Harden the runner'
        required: false
        default: true
        type: boolean

permissions: {}

concurrency:
  group: codacy-${{ github.repository }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  codacy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      if: ${{ inputs.harden_runner != false }}
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@3ad04f4ce2ebda15114704d442b57ef1def660fc # v4.4.4
      with:
        output: codacy.sarif
        format: sarif
        gh-code-scanning-compat: true

    - name: Upload results to code-scanning
      uses: github/codeql-action/upload-sarif@2d790406f505036ef40ecba973cc774a50395aac # v3.25.13
      with:
        sarif_file: codacy.sarif
