name: Dependency Scanning
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
    - main

  workflow_call:
    inputs:
      severity:
        description: Severity to fail on from low, moderate, high, or critical
        required: false
        type: string
        default: low
      comment:
        description: Comment on PR, from never, always, or on-failure
        required: false
        type: string
        default: on-failure
      harden_runner:
        description: "Harden the runner"
        required: false
        default: true
        type: boolean

permissions: {}

concurrency:
  group: dependency-review-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4
      if: ${{ inputs.harden_runner != false }}
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Checkout Repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

    - name: Dependency Review
      uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b
      with:
        fail-on-severity: ${{ inputs.severity || 'low' }}
        comment-summary-in-pr: ${{ inputs.comment || 'always' }}
