name: Dependency Scanning
on:
  workflow_call:
    inputs:
      severity:
        description: Severity to fail on from low, moderate, high, or critical
        required: false
        type: string
        default: low

      comment:
        description: Comment on PR, from never, always, or on-failure
        required: false
        type: string
        default: on-failure

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Dependency Review
      uses: actions/dependency-review-action@9129d7d40b8c12c1ed0f60400d00c92d437adcce
      with:
        fail-on-severity: ${{ inputs.severity }}
        comment-summary-in-pr: ${{ inputs.comment }}
