name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: '00 7 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, edited]
    paths:
      - '.github/workflows/security-ossf-scorecard.yml'


  workflow_call:
    inputs:
      harden_runner:
        description: "Harden the runner"
        required: false
        default: true
        type: boolean
    secrets:
      scorecard_token:
        description: "Token for the scorecard action"
        required: true

permissions: {}

concurrency:
  group: ossf-scorecard-${{ github.repository }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
        if: ${{ inputs.harden_runner != false }}
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            api.scorecard.dev:443
            api.securityscorecards.dev:443
            bestpractices.coreinfrastructure.org:443
            fulcio.sigstore.dev:443
            github.com:443
            mcr.microsoft.com:443
            oss-fuzz-build-logs.storage.googleapis.com:443
            rekor.sigstore.dev:443
            sigstore-tuf-root.storage.googleapis.com:443
            tuf-repo-cdn.sigstore.dev:443
            www.bestpractices.dev:443

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534
        with:
          results_file: ossf-scorecard.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN || secrets.scorecard_token }}
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: SARIF file
          path: ossf-scorecard.sarif
          retention-days: 5

      - name: Upload results to code-scanning
        uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251
        with:
          sarif_file: ossf-scorecard.sarif
